In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

# For regression:
import statsmodels.api as sm
from scipy import stats
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import matplotlib.dates as mdates
df = pd.read_csv(r"C:\BIT_Data_analyst\06_machine learning\06_lesson\customers.csv")

In [2]:
# create a sample dataframe
import pandas as pd
 
songs_dict = {
                'Customer': ['Aria', 'Aria', 'Aria', 'Chord', 'Chord', 'Harmony', 'Harmony', 'Harmony', 'Melody', 'Reed'],
                'Genre': ['Pop', 'Indie', 'Rock', 'Pop', 'Indie', 'Pop', 'Indie', 'Rock', 'Rock', 'Rock'],
                '# Songs': [50, 48, 1, 15, 36, 10, 5, 3, 2, 5]
             }
 
df = pd.DataFrame(songs_dict)
df

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [3]:
df.groupby('Customer')['# Songs'].sum()

Customer
Aria       99
Chord      51
Harmony    18
Melody      2
Reed        5
Name: # Songs, dtype: int64

In [4]:
# use group by to sum up the songs for each customer
customers_songs = (df.groupby('Customer')['# Songs']
   .sum()
   .reset_index())
customers_songs

  Customer  # Songs
0     Aria       99
1    Chord       51
2  Harmony       18
3   Melody        2
4     Reed        5

In [5]:
df.pivot(index='Customer', columns='Genre', values='# Songs')

Genre     Indie   Pop  Rock
Customer
Aria       48.0  50.0   1.0
Chord      36.0  15.0   NaN
Harmony     5.0  10.0   3.0
Melody      NaN   NaN   2.0
Reed        NaN   NaN   5.0

In [6]:
# add on a fillna to remove the NaN values
(df.pivot(index='Customer',
          columns='Genre',
          values='# Songs')
    .fillna(0))

Genre     Indie   Pop  Rock
Customer
Aria       48.0  50.0   1.0
Chord      36.0  15.0   0.0
Harmony     5.0  10.0   3.0
Melody      0.0   0.0   2.0
Reed        0.0   0.0   5.0

In [7]:
# add on a reset_index to remove the multi-index
(df.pivot(index='Customer',
          columns='Genre',
          values='# Songs')
    .fillna(0)
    .reset_index())

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

In [8]:
# save the results as a new dataframe
customers_genres = (df.pivot(index='Customer',
                             columns='Genre',
                             values='# Songs')
                      .fillna(0)
                      .reset_index())
customers_genres

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

In [11]:
# create a dataframe that will hold clean data
customers = df.copy()
customers

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [12]:
# rows with null values
customers.isna().any(axis=1)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [14]:
customers.dropna()

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [15]:
# and also remove the extra column
customers.dropna().reset_index(drop=True)

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [16]:
customers_dropped_rows

NameError: name 'customers_dropped_rows' is not defined

In [17]:
customers[['Age', 'Followers']]

KeyError: "None of [Index(['Age', 'Followers'], dtype='str')] are in the [columns]"

In [18]:
customers.Age.fillna(customers.Age.median())

AttributeError: 'DataFrame' object has no attribute 'Age'

In [19]:
round(customers.Age.fillna(customers.Age.median()))

AttributeError: 'DataFrame' object has no attribute 'Age'

In [20]:
customers.Followers.fillna(0)

AttributeError: 'DataFrame' object has no attribute 'Followers'

In [21]:
customers.Age = round(customers.Age.fillna(customers.Age.median()))
customers.Followers = customers.Followers.fillna(0)

AttributeError: 'DataFrame' object has no attribute 'Age'